/**
 * CV Generator Component
 *
 * Provides UI for generating CV from JSON data and uploading to forms
 */

import React, { useEffect, useState, useRef, useCallback } from 'react'
import { useCVWorkflow, useCVDataStatus } from '../../hooks/useCVWorkflow'
import { downloadPDFBlob, getPDFSize } from '../../../utils/directCDP'
import { getCVData, saveCVData } from '../../../utils/storageHelpers'
import { generateHTMLCV, downloadHTMLCV, downloadHTMLAsPDF } from '../../../utils/cvHTMLTemplate'
import { SkillsEditor, Skills } from './SkillsEditor'
import * as pdfjsLib from 'pdfjs-dist'
import './CVGenerator.css'

// Set up PDF.js worker
const workerSrc = chrome.runtime.getURL('pdf.worker.min.mjs')
pdfjsLib.GlobalWorkerOptions.workerSrc = workerSrc
console.log('[CVGenerator] PDF.js worker configured:', workerSrc)

export interface CVGeneratorProps {
  filename?: string
  showDownloadButton?: boolean
  showUploadButton?: boolean
  autoGenerate?: boolean
  onGenerateComplete?: (result: any) => void
}

export const CVGenerator: React.FC<CVGeneratorProps> = ({
  filename = 'cv.pdf',
  showDownloadButton = true,
  showUploadButton = false,
  autoGenerate = true,
  onGenerateComplete
}) => {
  const { state, generateAndDownloadCV, generateAndUploadCV } = useCVWorkflow()
  const { hasCVData, checking, checkStatus } = useCVDataStatus()
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const [pdfDoc, setPdfDoc] = useState<pdfjsLib.PDFDocumentProxy | null>(null)
  const [pageNum, setPageNum] = useState(1)
  const [numPages, setNumPages] = useState(0)
  const [scale, setScale] = useState(1.0)
  const [cvData, setCvData] = useState<any>(null)
  const [showJsonData, setShowJsonData] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [showSkillsEditor, setShowSkillsEditor] = useState(false)
  const [localPdfBlob, setLocalPdfBlob] = useState<Blob | null>(null)

  // 🔑 Track current render task to cancel previous ones
  const renderTaskRef = useRef<any>(null)
  const isRenderingRef = useRef(false)

  useEffect(() => {
    // Check CV data status on mount
    checkStatus()

    // Also load CV data for display
    loadCVData()
  }, [checkStatus])

  // Auto-generate PDF on mount when CV data exists and autoGenerate is enabled
  useEffect(() => {
    if (autoGenerate && hasCVData && !autoGenerated && !state.loading) {
      const autoGeneratePDF = async () => {
        setAutoGenerated(true)
        await generateAndDownloadCV(filename)
      }
      autoGeneratePDF()
    }
  }, [autoGenerate, hasCVData, autoGenerated, state.loading])

  const loadCVData = async () => {
    try {
      const data = await getCVData()
      setCvData(data)
    } catch (error) {
      console.error('Failed to load CV data:', error)
    }
  }

  const handleSaveSkills = async (updatedSkills: Skills) => {
    try {
      // Update CV data with edited skills
      const updatedCVData = {
        ...cvData,
        skills: updatedSkills
      }

      // Save to storage
      await saveCVData(updatedCVData)

      // Update local state
      setCvData(updatedCVData)
      setShowSkillsEditor(false)

      console.log('[CVGenerator] Skills saved successfully')
    } catch (error) {
      console.error('[CVGenerator] Failed to save skills:', error)
      alert('Failed to save skills. Please try again.')
    }
  }

  const handleDownloadHTML = () => {
    if (!cvData) {
      alert('No CV data available')
      return
    }

    try {
      const htmlCV = generateHTMLCV(cvData)
      downloadHTMLCV(htmlCV, 'cv.html')
      console.log('[CVGenerator] HTML CV downloaded successfully')
    } catch (error) {
      console.error('[CVGenerator] Failed to generate HTML CV:', error)
      alert('Failed to generate HTML CV. Please try again.')
    }
  }

  const handleDownloadHTMLAsPDF = () => {
    if (!cvData) {
      alert('No CV data available')
      return
    }

    try {
      const htmlCV = generateHTMLCV(cvData)
      downloadHTMLAsPDF(htmlCV)
      console.log('[CVGenerator] HTML to PDF conversion triggered')
    } catch (error) {
      console.error('[CVGenerator] Failed to convert HTML to PDF:', error)
      alert('Failed to convert HTML to PDF. Please try again.')
    }
  }

  // Helper: Wait for tab to complete loading
  const waitForTabComplete = async (tabId: number, timeout = 15000) => {
    const start = Date.now()
    while (Date.now() - start < timeout) {
      const tab = await chrome.tabs.get(tabId)
      if (tab.status === 'complete') return
      await new Promise(r => setTimeout(r, 100))
    }
    throw new Error('Tab did not load in time')
  }

  // Generate CV PDF with Puppeteer
  const handleGenerateCV = async () => {
    console.log('🚀 [PDF Gen] Starting PDF generation...')

    if (!cvData) {
      console.error('❌ [PDF Gen] No CV data available')
      alert('No CV data available')
      return
    }

    console.log('✅ [PDF Gen] CV Data found:', {
      hasPersonal: !!cvData.personal,
      hasExperience: cvData.experience?.length || 0,
      hasEducation: cvData.education?.length || 0,
      hasProjects: cvData.projects?.length || 0,
      hasSkills: !!cvData.skills
    })
    console.log('📋 [PDF Gen] CV Data sample:', JSON.stringify({
      personal: cvData.personal,
      professional: cvData.professional,
      experienceCount: cvData.experience?.length || 0
    }, null, 2))

    try {
      // 1. Generate HTML
      console.log('📝 [PDF Gen] Step 1: Generating HTML from CV data...')
      const html = generateHTMLCV(cvData)
      console.log('✅ [PDF Gen] HTML generated:', html.length, 'bytes')
      console.log('📋 [PDF Gen] HTML preview (first 300 chars):', html.substring(0, 300))

      const dataUrl = 'data:text/html;charset=utf-8,' + encodeURIComponent(html)
      console.log('✅ [PDF Gen] Data URL created, length:', dataUrl.length)

      // 2. Create tab
      console.log('🔌 [PDF Gen] Step 2: Creating new tab...')
      const tab = await chrome.tabs.create({ url: dataUrl, active: false })
      console.log('✅ [PDF Gen] Tab created, ID:', tab.id)

      // 3. Wait for tab to load
      console.log('⏳ [PDF Gen] Step 3: Waiting for tab to load...')
      await waitForTabComplete(tab.id!)
      console.log('✅ [PDF Gen] Tab loading complete')

      console.log('⏳ [PDF Gen] Waiting 2s for rendering...')
      await new Promise(r => setTimeout(r, 2000))
      console.log('✅ [PDF Gen] Render wait complete')

      // 4. Attach debugger and generate PDF
      console.log('🔧 [PDF Gen] Step 4: Attaching debugger...')

      // Try to detach if already attached (prevents "already attached" error)
      try {
        await chrome.debugger.detach({ tabId: tab.id! })
        console.log('🔧 [PDF Gen] Detached existing debugger')
      } catch (e) {
        // No debugger attached, that's fine
        console.log('🔧 [PDF Gen] No existing debugger to detach')
      }

      await chrome.debugger.attach({ tabId: tab.id! }, '1.3')
      console.log('✅ [PDF Gen] Debugger attached')

      try {
        console.log('⏳ [PDF Gen] Enabling Page domain...')
        await chrome.debugger.sendCommand({ tabId: tab.id! }, 'Page.enable')
        console.log('✅ [PDF Gen] Page domain enabled')

        console.log('⏳ [PDF Gen] Waiting 500ms for Page to settle...')
        await new Promise(r => setTimeout(r, 500))
        console.log('✅ [PDF Gen] Ready to generate PDF')

        console.log('📄 [PDF Gen] Step 5: Calling Page.printToPDF...')
        const result = await chrome.debugger.sendCommand(
          { tabId: tab.id! },
          'Page.printToPDF',
          {
            landscape: false,
            displayHeaderFooter: false,
            printBackground: true,
            preferCSSPageSize: false,
            paperWidth: 8.27,
            paperHeight: 11.69,
            marginTop: 0.5,
            marginBottom: 0.5,
            marginLeft: 0.5,
            marginRight: 0.5
          }
        ) as { data: string }

        console.log('✅ [PDF Gen] PDF generated! Base64 length:', result.data.length)
        console.log('📊 [PDF Gen] PDF base64 preview (first 100 chars):', result.data.substring(0, 100))

        // 5. Convert to blob
        console.log('🔄 [PDF Gen] Step 6: Converting base64 to blob...')
        const binary = atob(result.data)
        console.log('✅ [PDF Gen] Decoded binary string length:', binary.length)

        const bytes = new Uint8Array(binary.length)
        for (let i = 0; i < binary.length; i++) {
          bytes[i] = binary.charCodeAt(i)
        }
        console.log('✅ [PDF Gen] Uint8Array created, length:', bytes.length)

        const pdfBlob = new Blob([bytes], { type: 'application/pdf' })
        console.log('✅ [PDF Gen] Blob created:', {
          size: pdfBlob.size,
          type: pdfBlob.type,
          sizeKB: (pdfBlob.size / 1024).toFixed(2) + ' KB'
        })

        // 6. Set for canvas rendering
        console.log('🎨 [PDF Gen] Step 7: Setting blob for rendering...')
        setLocalPdfBlob(pdfBlob)
        console.log('✅ [PDF Gen] Blob state updated')

        // 7. Close tab
        console.log('🗑️ [PDF Gen] Step 8: Closing tab in 1s...')
        setTimeout(() => chrome.tabs.remove(tab.id!), 1000)

        alert(`✅ PDF Generated!\n\nSize: ${(pdfBlob.size / 1024).toFixed(2)} KB`)
        console.log('🎉 [PDF Gen] COMPLETE SUCCESS!')

      } finally {
        console.log('🔓 [PDF Gen] Detaching debugger...')
        await chrome.debugger.detach({ tabId: tab.id! })
        console.log('✅ [PDF Gen] Debugger detached')
      }

    } catch (error) {
      console.error('❌ [PDF Gen] ERROR:', error)
      console.error('❌ [PDF Gen] Error details:', {
        message: error instanceof Error ? error.message : 'Unknown',
        stack: error instanceof Error ? error.stack : undefined
      })
      alert('Failed: ' + (error instanceof Error ? error.message : 'Unknown error'))
    }
  }

  // Test: Same as above but for testing
  const handleTestPuppeteerPDF = async () => {
    if (!cvData) return

    try {
      const html = generateHTMLCV(cvData)
      const dataUrl = 'data:text/html;charset=utf-8,' + encodeURIComponent(html)
      const tab = await chrome.tabs.create({ url: dataUrl, active: false })

      await waitForTabComplete(tab.id!)
      await new Promise(r => setTimeout(r, 2000))

      // Try to detach if already attached
      try {
        await chrome.debugger.detach({ tabId: tab.id! })
      } catch (e) {
        // Ignore
      }

      await chrome.debugger.attach({ tabId: tab.id! }, '1.3')

      try {
        await chrome.debugger.sendCommand({ tabId: tab.id! }, 'Page.enable')
        await new Promise(r => setTimeout(r, 500))

        const result = await chrome.debugger.sendCommand(
          { tabId: tab.id! },
          'Page.printToPDF',
          {
            landscape: false,
            displayHeaderFooter: false,
            printBackground: true,
            preferCSSPageSize: false,
            paperWidth: 8.27,
            paperHeight: 11.69,
            marginTop: 0.5,
            marginBottom: 0.5,
            marginLeft: 0.5,
            marginRight: 0.5
          }
        ) as { data: string }

        const binary = atob(result.data)
        const bytes = new Uint8Array(binary.length)
        for (let i = 0; i < binary.length; i++) {
          bytes[i] = binary.charCodeAt(i)
        }
        const pdfBlob = new Blob([bytes], { type: 'application/pdf' })

        setLocalPdfBlob(pdfBlob)
        setTimeout(() => chrome.tabs.remove(tab.id!), 1000)

        alert(`✅ PDF: ${(pdfBlob.size / 1024).toFixed(2)} KB`)

      } finally {
        await chrome.debugger.detach({ tabId: tab.id! })
      }
    } catch (error) {
      alert('Failed: ' + (error instanceof Error ? error.message : 'Unknown'))
    }
  }

  // Render PDF when blob is ready (from both workflow and local generation)
  useEffect(() => {
    console.log('[CVGenerator] State update:', {
      success: state.success,
      hasPdfBlob: !!state.pdfBlob,
      hasLocalPdfBlob: !!localPdfBlob,
      pdfSize: state.pdfSize,
      pdfBlobDetails: state.pdfBlob ? {
        size: state.pdfBlob.size,
        type: state.pdfBlob.type
      } : null,
      localPdfBlobDetails: localPdfBlob ? {
        size: localPdfBlob.size,
        type: localPdfBlob.type
      } : null
    })

    // Render from workflow PDF
    if (state.success && state.pdfBlob) {
      console.log('[CVGenerator] Rendering PDF from workflow blob')
      renderPDF(state.pdfBlob)
    }
    // Render from local PDF generation
    else if (localPdfBlob) {
      console.log('[CVGenerator] Rendering PDF from local generation')
      renderPDF(localPdfBlob)
    }
    else if (state.success && !state.pdfBlob) {
      console.warn('[CVGenerator] State is success but no PDF blob!')
    }
  }, [state.success, state.pdfBlob, localPdfBlob])

  // Callback ref: fires as soon as canvas mounts into the DOM
  const canvasCallbackRef = useCallback((node: HTMLCanvasElement | null) => {
    canvasRef.current = node
    console.log('[CVGenerator] Canvas callback ref called, node:', !!node, 'pdfDoc:', !!pdfDoc)
    // Don't render here - let the useEffect handle it to avoid duplicate renders
  }, [])

  // 🔑 NEW: Render page whenever pdfDoc changes (even if canvas already mounted)
  useEffect(() => {
    console.log('[CVGenerator] ========== pdfDoc useEffect ==========')
    console.log('[CVGenerator] pdfDoc:', !!pdfDoc)
    console.log('[CVGenerator] canvasRef.current:', !!canvasRef.current)
    console.log('[CVGenerator] numPages:', numPages)
    console.log('[CVGenerator] isRendering:', isRenderingRef.current)

    if (pdfDoc && canvasRef.current && !isRenderingRef.current) {
      console.log('[CVGenerator] ✅ Ready to render! Waiting a bit for canvas to be ready...')

      // Use setTimeout to ensure canvas is fully mounted and ready
      setTimeout(() => {
        console.log('[CVGenerator] Now rendering page 1...')
        renderPage(pdfDoc, 1, scale)
      }, 100)
    } else {
      console.log('[CVGenerator] ⏳ Not ready to render...')
      if (!pdfDoc) {
        console.log('[CVGenerator] - pdfDoc is null/undefined')
      }
      if (!canvasRef.current) {
        console.log('[CVGenerator] - canvasRef.current is null')
      }
      if (isRenderingRef.current) {
        console.log('[CVGenerator] - Already rendering, waiting...')
      }
    }
  }, [pdfDoc, scale, numPages])

  const renderPDF = async (pdfBlob: Blob) => {
    try {
      console.log('[CVGenerator] ========== renderPDF called ==========')
      console.log('[CVGenerator] PDF Blob received:', {
        size: pdfBlob.size,
        sizeKB: (pdfBlob.size / 1024).toFixed(2) + ' KB',
        type: pdfBlob.type,
        isBlob: pdfBlob instanceof Blob
      })

      if (pdfBlob.size === 0) {
        console.error('[CVGenerator] ❌ PDF blob is empty!')
        return
      }

      console.log('[CVGenerator] Creating ArrayBuffer...')
      const arrayBuffer = await pdfBlob.arrayBuffer()
      console.log('[CVGenerator] ArrayBuffer created:', {
        byteLength: arrayBuffer.byteLength
      })

      console.log('[CVGenerator] Loading PDF with PDF.js...')
      const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer })

      loadingTask.promise.then(
        (pdf) => {
          console.log('[CVGenerator] ✅ PDF document loaded:', {
            numPages: pdf.numPages,
            pdf: pdf
          })
        },
        (error) => {
          console.error('[CVGenerator] ❌ PDF loading task failed:', error)
        }
      )

      const pdf = await loadingTask.promise

      console.log('[CVGenerator] PDF loaded successfully, pages:', pdf.numPages)
      console.log('[CVGenerator] Setting pdfDoc state...')

      setPdfDoc(pdf)
      setNumPages(pdf.numPages)
      setPageNum(1)

      console.log('[CVGenerator] State setters called. React should re-render now.')

      console.log('[CVGenerator] ✅ renderPDF complete! Canvas should render soon.')

    } catch (error) {
      console.error('[CVGenerator] ❌ Failed to render PDF:', error)
    }
  }

  const renderPage = async (pdf: pdfjsLib.PDFDocumentProxy, pageNumber: number, scale: number) => {
    const canvas = canvasRef.current
    if (!canvas) {
      console.error('[CVGenerator] Canvas ref not found!')
      return
    }

    // 🔑 Cancel previous render if still running
    if (renderTaskRef.current) {
      console.log('[CVGenerator] Cancelling previous render task...')
      try {
        renderTaskRef.current.cancel('New render requested')
      } catch (e) {
        console.warn('[CVGenerator] Cancel warning:', e)
      }
      renderTaskRef.current = null
    }

    // Check if already rendering
    if (isRenderingRef.current) {
      console.log('[CVGenerator] Already rendering, waiting...')
      await new Promise(resolve => setTimeout(resolve, 100))
    }

    isRenderingRef.current = true

    try {
      const page = await pdf.getPage(pageNumber)

      // Account for devicePixelRatio for crisp rendering on HiDPI/Retina screens
      const dpr = window.devicePixelRatio || 1
      const viewport = page.getViewport({ scale: scale * dpr })

      console.log('[CVGenerator] Page viewport:', {
        width: viewport.width,
        height: viewport.height,
        scale,
        dpr
      })

      const context = canvas.getContext('2d')
      if (!context) {
        console.error('[CVGenerator] Could not get canvas 2D context!')
        return
      }

      // Canvas pixel buffer = logical size × DPR (high resolution)
      canvas.width = viewport.width
      canvas.height = viewport.height

      // CSS display size = logical size (keeps layout correct)
      canvas.style.width = `${viewport.width / dpr}px`
      canvas.style.height = `${viewport.height / dpr}px`

      console.log('[CVGenerator] Canvas dimensions set:', {
        bufferWidth: canvas.width,
        bufferHeight: canvas.height,
        cssWidth: canvas.style.width,
        cssHeight: canvas.style.height,
        dpr
      })

      // Clear canvas before rendering
      context.clearRect(0, 0, canvas.width, canvas.height)

      // Fill with white background to ensure visibility
      context.fillStyle = '#ffffff'
      context.fillRect(0, 0, canvas.width, canvas.height)

      const renderContext = {
        canvasContext: context,
        viewport: viewport,
        canvas: canvas
      }

      console.log('[CVGenerator] Starting page render...')
      const renderTask = page.render(renderContext)

      // Store render task for cancellation
      renderTaskRef.current = renderTask

      await renderTask.promise
      renderTaskRef.current = null

      console.log('[CVGenerator] ✅ Page rendered successfully:', pageNumber, {
        width: canvas.width,
        height: canvas.height,
        scale,
        dpr
      })
    } catch (error) {
      const errorMsg = error && typeof error === 'object' && 'message' in error ? (error as { message: string }).message : 'Unknown error'

      if (errorMsg.includes('cancelled')) {
        console.log('[CVGenerator] Render cancelled (expected)')
        return
      }

      console.error('[CVGenerator] Failed to render page:', pageNumber, error)
      // Show error on canvas
      const context = canvas.getContext('2d')
      if (context) {
        context.fillStyle = '#ffebee'
        context.fillRect(0, 0, canvas.width || 300, canvas.height || 150)
        context.fillStyle = '#c62828'
        context.font = '14px sans-serif'
        context.fillText('PDF rendering failed', 10, 30)
        context.fillText(errorMsg, 10, 50)
      }
    } finally {
      isRenderingRef.current = false
    }
  }

  const handlePrevPage = () => {
    if (pageNum <= 1) return
    const newPage = pageNum - 1
    setPageNum(newPage)
    if (pdfDoc) {
      renderPage(pdfDoc, newPage, scale)
    }
  }

  const handleNextPage = () => {
    if (pageNum >= numPages) return
    const newPage = pageNum + 1
    setPageNum(newPage)
    if (pdfDoc) {
      renderPage(pdfDoc, newPage, scale)
    }
  }

  const handleZoomIn = () => {
    const newScale = scale + 0.25
    setScale(newScale)
    if (pdfDoc) {
      renderPage(pdfDoc, pageNum, newScale)
    }
  }

  const handleZoomOut = () => {
    if (scale <= 0.5) return
    const newScale = scale - 0.25
    setScale(newScale)
    if (pdfDoc) {
      renderPage(pdfDoc, pageNum, newScale)
    }
  }

  useEffect(() => {
    // Notify parent when generation completes
    if (state.success && onGenerateComplete) {
      onGenerateComplete({
        stagesCompleted: state.stagesCompleted,
        pdfSize: state.pdfSize,
        uploadStats: state.uploadStats
      })
    }
  }, [state.success, state.stagesCompleted, state.pdfSize, state.uploadStats, onGenerateComplete])

  // Only show "no data" state if we're done checking and there's no data
  // Don't block rendering if PDF is already generated
  if (!checking && !hasCVData && !pdfDoc && !state.loading && !state.success) {
    return (
      <div className="cv-generator cv-generator--no-data">
        <div className="cv-generator__icon">📄</div>
        <div className="cv-generator__message">
          No CV data found
        </div>
        <div className="cv-generator__hint">
          Please upload your CV first to generate PDF
        </div>
      </div>
    )
  }

  // Show checking state only if nothing else is happening
  if (checking && !state.loading && !pdfDoc && !state.success) {
    return (
      <div className="cv-generator cv-generator--checking">
        <div className="cv-generator__status">Checking CV data...</div>
      </div>
    )
  }

  return (
    <div className="cv-generator">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div className="cv-generator__header">
          <h3>Generate CV PDF</h3>
          <p className="cv-generator__description">
            Create a professional PDF from your CV data
          </p>
        </div>
        <div>
          {state.pdfSize && (
            <div className="cv-generator__pdf-size">
              📊 {state.pdfSize}
            </div>
          )}
        </div>
      </div>

      {/* Embedded PDF Viewer */}
      {pdfDoc && (
        <div className="cv-generator__pdf-viewer-section">
          <div className="cv-generator__pdf-controls">
            <button onClick={handlePrevPage} disabled={pageNum <= 1}>← Previous</button>
            <span>Page {pageNum} of {numPages}</span>
            <button onClick={handleNextPage} disabled={pageNum >= numPages}>Next →</button>
            <button onClick={handleZoomOut} disabled={scale <= 0.5}>−</button>
            <span>{Math.round(scale * 100)}%</span>
            <button onClick={handleZoomIn}>+</button>
          </div>
          <div className="cv-generator__pdf-viewer-container">
            <canvas
              ref={canvasCallbackRef}
              className="cv-generator__pdf-canvas"
            />
          </div>
        </div>
      )}

      {/* Loading State for PDF Generation */}
      {state.loading && !pdfDoc && (
        <div className="cv-generator__pdf-viewer-section">
          <div className="cv-generator__pdf-viewer-loading">
            <div className="cv-generator__spinner"></div>

            <p className="cv-generator__progress-text">{state.progress}</p>
          </div>
        </div>
      )}


      {/* Progress / Status */}
      {state.loading && (
        <div className="cv-generator__progress">
          <div className="cv-generator__spinner"></div>
          <div className="cv-generator__progress-text">{state.progress}</div>
          {state.stagesCompleted.length > 0 && (
            <div className="cv-generator__stages">
              Completed: {state.stagesCompleted.join(' → ')}
            </div>
          )}
        </div>
      )}

      {/* Success Message */}
      {state.success && !state.loading && (
        <div className="cv-generator__success">
          <div className="cv-generator__success-icon">✓</div>
          <div className="cv-generator__success-text">
            {state.progress}
          </div>
          {state.uploadStats && (
            <div className="cv-generator__upload-stats">
              Uploaded to {state.uploadStats.uploaded} field(s)
              {state.uploadStats.errors.length > 0 && (
                <div className="cv-generator__errors">
                  {state.uploadStats.errors.map((error, i) => (
                    <div key={i} className="cv-generator__error">
                      ⚠️ {error}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Error Message */}
      {state.error && !state.loading && (
        <div className="cv-generator__error">
          <div className="cv-generator__error-icon">⚠️</div>
          <div className="cv-generator__error-text">{state.error}</div>
        </div>
      )}

      {/* Action Buttons */}
      {!state.loading && (
        <div className="cv-generator__actions">
          {/* Main Generate CV button - Now uses Puppeteer (reliable!) */}
          <button
            className="cv-generator__button cv-generator__button--download"
            onClick={handleGenerateCV}
            disabled={!cvData}
            style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}
          >
            <span className="cv-generator__button-icon">✨</span>
            <span>Generate CV (Puppeteer)</span>
          </button>

          {showDownloadButton && (state.pdfBlob || localPdfBlob) && (
            <button
              className="cv-generator__button cv-generator__button--download"
              onClick={() => {
                const blobToDownload = localPdfBlob || state.pdfBlob
                console.log('Download Blob', blobToDownload)
                if (blobToDownload) {
                  downloadPDFBlob(blobToDownload, filename)
                }
              }}
              disabled={!state.pdfBlob && !localPdfBlob}
            >
              <span className="cv-generator__button-icon">⬇️</span>
              <span>Download PDF</span>
            </button>
          )}

          <button
            className="cv-generator__button cv-generator__button--html"
            onClick={handleDownloadHTML}
            disabled={!cvData}
          >
            <span className="cv-generator__button-icon">🌐</span>
            <span>Download HTML</span>
          </button>

          <button
            className="cv-generator__button cv-generator__button--html"
            onClick={handleTestPuppeteerPDF}
            disabled={!cvData}
            style={{ background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' }}
          >
            <span className="cv-generator__button-icon">🔄</span>
            <span>Regenerate (Puppeteer)</span>
          </button>

          {showUploadButton && (
            <button
              className="cv-generator__button cv-generator__button--upload"
              onClick={() => generateAndUploadCV(filename)}
              disabled={state.loading}
            >
              <span className="cv-generator__button-icon">📤</span>
              <span>Generate & Upload</span>
            </button>
          )}
        </div>
      )}

      {/* Info Section */}
      <div className="cv-generator__info">
        <details>
          <summary>What happens when you generate CV?</summary>
          <ol className="cv-generator__steps">
            <li>📥 Fetch your CV data from storage</li>
            <li>🌐 Generate HTML from your CV</li>
            <li>📄 Use Puppeteer (Chrome native) to create PDF</li>
            <li>🖼️ Display PDF in canvas viewer above</li>
            <li>💾 Download PDF or HTML anytime</li>
          </ol>
        </details>
      </div>

      {/* Skills Editor Modal */}
      {showSkillsEditor && (
        <div className="cv-generator__modal-overlay" onClick={() => setShowSkillsEditor(false)}>
          <div className="cv-generator__modal-content" onClick={(e) => e.stopPropagation()}>
            <SkillsEditor
              skills={cvData?.skills || {}}
              onSave={handleSaveSkills}
              onCancel={() => setShowSkillsEditor(false)}
            />
          </div>
        </div>
      )}
    </div>
  )
}

export default CVGenerator
