/**
 * CV Generator Component
 *
 * Provides UI for generating CV from JSON data and uploading to forms
 */

import React, { useEffect, useState, useRef } from 'react'
import { useCVWorkflow, useCVDataStatus } from '../../hooks/useCVWorkflow'
import { downloadPDFBlob } from '../../../utils/pdfCompiler'
import { getCVData, saveCVData } from '../../../utils/storageHelpers'
import { SkillsEditor, Skills } from './SkillsEditor'
import * as pdfjsLib from 'pdfjs-dist'
import './CVGenerator.css'

// Set up PDF.js worker
pdfjsLib.GlobalWorkerOptions.workerSrc = chrome.runtime.getURL('pdf.worker.min.mjs')

export interface CVGeneratorProps {
  filename?: string
  showDownloadButton?: boolean
  showUploadButton?: boolean
  autoGenerate?: boolean
  onGenerateComplete?: (result: any) => void
}

export const CVGenerator: React.FC<CVGeneratorProps> = ({
  filename = 'cv.pdf',
  showDownloadButton = true,
  showUploadButton = false,
  autoGenerate = true,
  onGenerateComplete
}) => {
  const { state, generateAndDownloadCV, generateAndUploadCV } = useCVWorkflow()
  const { hasCVData, checking, checkStatus } = useCVDataStatus()
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [pdfDoc, setPdfDoc] = useState<pdfjsLib.PDFDocumentProxy | null>(null)
  const [pageNum, setPageNum] = useState(1)
  const [numPages, setNumPages] = useState(0)
  const [scale, setScale] = useState(1.5)
  const [cvData, setCvData] = useState<any>(null)
  const [showJsonData, setShowJsonData] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [showSkillsEditor, setShowSkillsEditor] = useState(false)

  useEffect(() => {
    // Check CV data status on mount
    checkStatus()

    // Also load CV data for display
    loadCVData()
  }, [checkStatus])

  // Auto-generate PDF on mount when CV data exists and autoGenerate is enabled
  useEffect(() => {
    if (autoGenerate && hasCVData && !autoGenerated && !state.loading) {
      const autoGeneratePDF = async () => {
        setAutoGenerated(true)
        await generateAndDownloadCV(filename)
      }
      autoGeneratePDF()
    }
  }, [autoGenerate, hasCVData, autoGenerated, state.loading])

  const loadCVData = async () => {
    try {
      const data = await getCVData()
      setCvData(data)
    } catch (error) {
      console.error('Failed to load CV data:', error)
    }
  }

  const handleSaveSkills = async (updatedSkills: Skills) => {
    try {
      // Update CV data with edited skills
      const updatedCVData = {
        ...cvData,
        skills: updatedSkills
      }

      // Save to storage
      await saveCVData(updatedCVData)

      // Update local state
      setCvData(updatedCVData)
      setShowSkillsEditor(false)

      console.log('[CVGenerator] Skills saved successfully')
    } catch (error) {
      console.error('[CVGenerator] Failed to save skills:', error)
      alert('Failed to save skills. Please try again.')
    }
  }

  // Render PDF when blob is ready
  useEffect(() => {
    console.log('[CVGenerator] State update:', {
      success: state.success,
      hasPdfBlob: !!state.pdfBlob,
      pdfSize: state.pdfSize
    })

    if (state.success && state.pdfBlob) {
      console.log('[CVGenerator] Rendering PDF from blob')
      renderPDF(state.pdfBlob)
    }
  }, [state.success, state.pdfBlob])

  const renderPDF = async (pdfBlob: Blob) => {
    try {
      const arrayBuffer = await pdfBlob.arrayBuffer()
      const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer })
      const pdf = await loadingTask.promise

      console.log('[CVGenerator] PDF loaded, pages:', pdf.numPages)
      setPdfDoc(pdf)
      setNumPages(pdf.numPages)
      setPageNum(1)

      // Render first page with better scaling
      await renderPage(pdf, 1, 1.0) // Start with scale 1.0
    } catch (error) {
      console.error('[CVGenerator] Failed to render PDF:', error)
    }
  }

  const renderPage = async (pdf: pdfjsLib.PDFDocumentProxy, pageNumber: number, scale: number) => {
    const canvas = canvasRef.current
    if (!canvas) return

    const page = await pdf.getPage(pageNumber)
    const viewport = page.getViewport({ scale })

    const context = canvas.getContext('2d')
    if (!context) return

    canvas.height = viewport.height
    canvas.width = viewport.width

    const renderContext = {
      canvasContext: context,
      viewport: viewport,
      canvas: canvas
    }

    await page.render(renderContext).promise
    console.log('[CVGenerator] Page rendered:', pageNumber)
  }

  const handlePrevPage = () => {
    if (pageNum <= 1) return
    const newPage = pageNum - 1
    setPageNum(newPage)
    if (pdfDoc) {
      renderPage(pdfDoc, newPage, scale)
    }
  }

  const handleNextPage = () => {
    if (pageNum >= numPages) return
    const newPage = pageNum + 1
    setPageNum(newPage)
    if (pdfDoc) {
      renderPage(pdfDoc, newPage, scale)
    }
  }

  const handleZoomIn = () => {
    const newScale = scale + 0.25
    setScale(newScale)
    if (pdfDoc) {
      renderPage(pdfDoc, pageNum, newScale)
    }
  }

  const handleZoomOut = () => {
    if (scale <= 0.5) return
    const newScale = scale - 0.25
    setScale(newScale)
    if (pdfDoc) {
      renderPage(pdfDoc, pageNum, newScale)
    }
  }

  useEffect(() => {
    // Notify parent when generation completes
    if (state.success && onGenerateComplete) {
      onGenerateComplete({
        stagesCompleted: state.stagesCompleted,
        pdfSize: state.pdfSize,
        uploadStats: state.uploadStats
      })
    }
  }, [state.success, state.stagesCompleted, state.pdfSize, state.uploadStats, onGenerateComplete])

  // Only show "no data" state if we're done checking and there's no data
  // Don't block rendering if PDF is already generated
  if (!checking && !hasCVData && !pdfDoc && !state.loading && !state.success) {
    return (
      <div className="cv-generator cv-generator--no-data">
        <div className="cv-generator__icon">📄</div>
        <div className="cv-generator__message">
          No CV data found
        </div>
        <div className="cv-generator__hint">
          Please upload your CV first to generate PDF
        </div>
      </div>
    )
  }

  // Show checking state only if nothing else is happening
  if (checking && !state.loading && !pdfDoc && !state.success) {
    return (
      <div className="cv-generator cv-generator--checking">
        <div className="cv-generator__status">Checking CV data...</div>
      </div>
    )
  }

  return (
    <div className="cv-generator">
      <div className="cv-generator__header">
        <h3>Generate CV PDF</h3>
        <p className="cv-generator__description">
          Create a professional PDF from your CV data
        </p>
      </div>

      {/* Embedded PDF Viewer */}
      {pdfDoc && (
        <div className="cv-generator__pdf-viewer-section">
          <div className="cv-generator__pdf-viewer-header">
            <h4>📄 CV PDF Preview</h4>
            <div className="cv-generator__pdf-size">
              {state.pdfSize || 'PDF Size: Loading...'}
            </div>
          </div>
          <div className="cv-generator__pdf-controls">
            <button onClick={handlePrevPage} disabled={pageNum <= 1}>← Previous</button>
            <span>Page {pageNum} of {numPages}</span>
            <button onClick={handleNextPage} disabled={pageNum >= numPages}>Next →</button>
            <button onClick={handleZoomOut} disabled={scale <= 0.5}>−</button>
            <span>{Math.round(scale * 100)}%</span>
            <button onClick={handleZoomIn}>+</button>
          </div>
          <div className="cv-generator__pdf-viewer-container">
            <canvas
              ref={canvasRef}
              className="cv-generator__pdf-canvas"
            />
          </div>
        </div>
      )}

      {/* Loading State for PDF Generation */}
      {state.loading && !pdfDoc && (
        <div className="cv-generator__pdf-viewer-section">
          <div className="cv-generator__pdf-viewer-loading">
            <div className="cv-generator__spinner"></div>
            <p>Generating PDF...</p>
            <p className="cv-generator__progress-text">{state.progress}</p>
          </div>
        </div>
      )}

      {/* CV Data Display */}
      {cvData && (
        <div className="cv-generator__data-section">
          <div className="cv-generator__data-header">
            <h4>📋 CV Data from Storage</h4>
            <div className="cv-generator__header-actions">
              {cvData.skills && typeof cvData.skills === 'object' && Object.keys(cvData.skills).length > 0 && (
                <button
                  className="cv-generator__toggle-btn cv-generator__toggle-btn--edit"
                  onClick={() => setShowSkillsEditor(true)}
                >
                  ✏️ Edit Skills
                </button>
              )}
              <button
                className="cv-generator__toggle-btn"
                onClick={() => setShowJsonData(!showJsonData)}
              >
                {showJsonData ? 'Hide' : 'Show'} JSON Data
              </button>
            </div>
          </div>

          {showJsonData && (
            <div className="cv-generator__json-content">
              <pre className="cv-generator__json-pre">
                {JSON.stringify(cvData, null, 2)}
              </pre>
            </div>
          )}

          <div className="cv-generator__data-summary">
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Name:</span>
              <span className="cv-generator__data-value">
                {cvData.personal?.firstName} {cvData.personal?.lastName}
              </span>
            </div>
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Email:</span>
              <span className="cv-generator__data-value">{cvData.personal?.email}</span>
            </div>
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Experience:</span>
              <span className="cv-generator__data-value">{cvData.experience?.length || 0} positions</span>
            </div>
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Education:</span>
              <span className="cv-generator__data-value">{cvData.education?.length || 0} entries</span>
            </div>
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Projects:</span>
              <span className="cv-generator__data-value">{cvData.projects?.length || 0} projects</span>
            </div>
            <div className="cv-generator__data-item">
              <span className="cv-generator__data-label">Skills:</span>
              <span className="cv-generator__data-value">
                {cvData.skills && typeof cvData.skills === 'object' ? Object.keys(cvData.skills).length : 0} categories
              </span>
            </div>

            {/* 🎯 Dynamic Skills Display */}
            {cvData.skills && typeof cvData.skills === 'object' && Object.keys(cvData.skills).length > 0 && (
              <div className="cv-generator__skills-section">
                <h5>🎯 Skills by Category</h5>
                {Object.entries(cvData.skills).map(([category, skills]) => (
                  <div key={category} className="cv-generator__skill-category">
                    <div className="cv-generator__category-name">
                      <strong>{category}</strong>
                      <span className="cv-generator__skill-count">({Array.isArray(skills) ? skills.length : 0} skills)</span>
                    </div>
                    <div className="cv-generator__skill-list">
                      {Array.isArray(skills) && skills.map((skill, index) => (
                        <span key={index} className="cv-generator__skill-tag">
                          {skill}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Progress / Status */}
      {state.loading && (
        <div className="cv-generator__progress">
          <div className="cv-generator__spinner"></div>
          <div className="cv-generator__progress-text">{state.progress}</div>
          {state.stagesCompleted.length > 0 && (
            <div className="cv-generator__stages">
              Completed: {state.stagesCompleted.join(' → ')}
            </div>
          )}
        </div>
      )}

      {/* Success Message */}
      {state.success && !state.loading && (
        <div className="cv-generator__success">
          <div className="cv-generator__success-icon">✓</div>
          <div className="cv-generator__success-text">
            {state.progress}
          </div>
          {state.pdfSize && (
            <div className="cv-generator__pdf-size">
              PDF Size: {state.pdfSize}
            </div>
          )}
          {state.uploadStats && (
            <div className="cv-generator__upload-stats">
              Uploaded to {state.uploadStats.uploaded} field(s)
              {state.uploadStats.errors.length > 0 && (
                <div className="cv-generator__errors">
                  {state.uploadStats.errors.map((error, i) => (
                    <div key={i} className="cv-generator__error">
                      ⚠️ {error}
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Error Message */}
      {state.error && !state.loading && (
        <div className="cv-generator__error">
          <div className="cv-generator__error-icon">⚠️</div>
          <div className="cv-generator__error-text">{state.error}</div>
        </div>
      )}

      {/* Action Buttons */}
      {!state.loading && (
        <div className="cv-generator__actions">
          {showDownloadButton && state.pdfBlob && (
            <button
              className="cv-generator__button cv-generator__button--download"
              onClick={() => {
                if (state.pdfBlob) {
                  downloadPDFBlob(state.pdfBlob, filename)
                }
              }}
              disabled={!state.pdfBlob}
            >
              <span className="cv-generator__button-icon">⬇️</span>
              <span>Download PDF</span>
            </button>
          )}

          {showUploadButton && (
            <button
              className="cv-generator__button cv-generator__button--upload"
              onClick={() => generateAndUploadCV(filename)}
              disabled={state.loading}
            >
              <span className="cv-generator__button-icon">📤</span>
              <span>Generate & Upload</span>
            </button>
          )}
        </div>
      )}

      {/* Info Section */}
      <div className="cv-generator__info">
        <details>
          <summary>What happens when you generate CV?</summary>
          <ol className="cv-generator__steps">
            <li>📥 Fetch your CV data from storage</li>
            <li>📝 Convert to LaTeX format</li>
            <li>📄 Compile LaTeX to PDF</li>
            <li>📥 Display PDF in viewer above</li>
          </ol>
        </details>
      </div>

      {/* Skills Editor Modal */}
      {showSkillsEditor && (
        <div className="cv-generator__modal-overlay" onClick={() => setShowSkillsEditor(false)}>
          <div className="cv-generator__modal-content" onClick={(e) => e.stopPropagation()}>
            <SkillsEditor
              skills={cvData?.skills || {}}
              onSave={handleSaveSkills}
              onCancel={() => setShowSkillsEditor(false)}
            />
          </div>
        </div>
      )}
    </div>
  )
}

export default CVGenerator
